### ISSUE TITLE
Why subtract zero from numbers?

### ISSUE THREAD

**Issue by aaronfranke** [RazerM/orbital#10]
I'm trying to understand the code [here](https://github.com/RazerM/orbital/blob/0.7.0/orbital/utilities.py#L269), but this is confusing me:

    abs(i - 0)

Why is the code written like this? Is there a reason why the `- 0` exists? Why not `abs(i)`? 

I posted a question on SO here: https://stackoverflow.com/questions/55683731/is-there-a-reason-to-subtract-zero-from-a-number-in-python

**Comment by RazerM** [comment]
There isn't a reason. I don't know what I was thinking at the time 😅
